version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"

    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
    restart: always

  kibana:
    image: kibana:7.12.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.12.1
    container_name: logstash
    volumes:
      - type: bind
        source: ./logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true

      - type: bind
        source: ./logstash/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
      - "9376:9376"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana

  elastalert:
    image: muhammetbolat/solid-elastalert
    container_name: elastalert
    volumes:
      - type: bind
        source: ./elastalert/config.yaml
        target: /home/elastalert/config.yaml
        read_only: true
      - type: bind
        source: ./elastalert/rules
        target: /home/elastalert/rules
        read_only: true

    ports: 
      - "3030:3030"
      - "3333:3333"
    
    networks:
        - elk
    depends_on:
        - elasticsearch
        - kibana
    restart: unless-stopped

volumes:
  es-bolates:
    driver: local

networks:
  elk:
    driver: bridge
 